language: node_js
sudo: false # use container based infrastructure
env:
    global:
        - TESTMODEL_URL=http://localhost:8080/intermine-demo
        - TESTMODEL_PATH=intermine-demo
before_install:
    - ./config/travis/init.sh
    - npm install bower
    - npm install -g codo
    - ./node_modules/.bin/bower install
script:
    - npm test
node_js:
    - '10.15.2'
jdk:
    - openjdk8
